import os

sitemap_urls = [
    "https://anfitriaopicarras.com/beto-carrero-world-diversao-garantida-para-todas-as-idades/",
    "https://anfitriaopicarras.com/hora-de-tirar-ferias/",
    "https://anfitriaopicarras.com/balneario-picarras-um-paraiso-a-beira-mar-em-santa-catarina/",
    "https://anfitriaopicarras.com/principais-vantagens-do-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/aluguel-de-verao-em-balneario-picarras-no-airbnb-o-guia-completo-para-encontrar-a-melhor-hospedagem/",
    "https://anfitriaopicarras.com/alugar-seu-imovel-ou-desfrutar/",
    "https://anfitriaopicarras.com/o-mercado-de-airbnb-no-brasil-em-2024-perspectivas-e-tendencias/",
    "https://anfitriaopicarras.com/o-que-e-um-airbnb-e-como-funciona-guia-completo-para-iniciantes/",
    "https://anfitriaopicarras.com/airbnb-o-que-e-como-funciona-e-como-comecar-a-usar/",
    "https://anfitriaopicarras.com/descubra-o-que-e-um-airbnb-e-como-ele-pode-transformar-suas-viagens/",
    "https://anfitriaopicarras.com/airbnb-descomplicado/",
    "https://anfitriaopicarras.com/como-funciona-o-airbnb-entenda-o-conceito-e-beneficios/",
    "https://anfitriaopicarras.com/o-que-e-airbnb-guia-essencial-para-hospedes-e-anfitrioes/",
    "https://anfitriaopicarras.com/ganhe-dinheiro-com-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/5-itens-essenciais-para-montar-um-imovel-de-airbnb/",
    "https://anfitriaopicarras.com/tudo-sobre-o-airbnb-o-guia-definitivo-para-hospedes-e-anfitrioes/",
    "https://anfitriaopicarras.com/as-vantagens-do-aluguel-de-temporada-para-imovel-parado/",
    "https://anfitriaopicarras.com/imovel-de-temporada-em-picarras-a-melhor-opcao-para-quem-busca-privacidade-e-conforto/",
    "https://anfitriaopicarras.com/passo-a-passo-para-alugar-no-airbnb-tudo-o-que-voce-precisa-saber/",
    "https://anfitriaopicarras.com/preparativos-essenciais-para-alugar-seu-espaco-no-airbnb/",
    "https://anfitriaopicarras.com/mensagem-de-boas-vindas-para-hospedes/",
    "https://anfitriaopicarras.com/praca-rippa-picarras-o-local-perfeito-para-comer-se-divertir-e-relaxar/",
    "https://anfitriaopicarras.com/marina-park-o-melhor-local-para-sua-experiencia-nautica-em-balneario-picarras/",
    "https://anfitriaopicarras.com/trilha-ecologica-morro-do-quininho-aventura-e-natureza-em-balneario-picarras/",
    "https://anfitriaopicarras.com/challenge-rock-o-templo-do-rock-em-balneario-picarras/",
    "https://anfitriaopicarras.com/investir-em-aluguel-de-temporada-em-picarras-e-um-bom-negocio/",
    "https://anfitriaopicarras.com/novidades-do-mercado-de-aluguel-de-temporada-em-2025/",
    "https://anfitriaopicarras.com/dicas-essenciais-para-o-proprietario-de-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/quanto-cobrar-na-diaria-do-seu-imovel-de-airbnb/",
    "https://anfitriaopicarras.com/administracao-airbnb-em-balneario-picarras/",
    "https://anfitriaopicarras.com/airbnb-anfitriao/",
    "https://anfitriaopicarras.com/como-se-destacar-e-maximizar-seus-lucros/",
    "https://anfitriaopicarras.com/como-ser-anfitriao-no-airbnb-e-ganhar-dinheiro-com-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/como-ser-anfitriao-no-airbnb-e-lucrar-com-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/co-anfitriao-no-airbnb-como-funciona-e-como-pode-ajudar-no-seu-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/co-anfitriao-no-airbnb/",
    "https://anfitriaopicarras.com/como-ser-anfitriao-no-airbnb-e-lucrar-com-aluguel-de-temporada-2/",
    "https://anfitriaopicarras.com/explorando-as-profundezas-a-experiencia-do-museu-oceanografico-da-univali/",
    "https://anfitriaopicarras.com/como-atrair-mais-hospedes-para-seu-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/guia-completo-para-ser-um-anfitriao-de-sucesso-em-picarras-2/",
    "https://anfitriaopicarras.com/dicas-essenciais-para-anfitrioes-de-airbnb-em-picarras/",
    "https://anfitriaopicarras.com/como-alugar-seu-imovel-em-picarras-e-atrair-mais-turistas/",
    "https://anfitriaopicarras.com/a-importancia-da-foto-no-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/guia-completo-para-ser-um-anfitriao-de-sucesso-em-picarras/",
    "https://anfitriaopicarras.com/aluguel-por-temporada-em-picarras-como-maximizar-seus-lucros/",
    "https://anfitriaopicarras.com/como-transformar-seu-imovel-de-temporada-em-picarras-em-um-investimento-lucrativo/",
    "https://anfitriaopicarras.com/como-ganhar-dinheiro-com-aluguel-por-temporada-5-estrategias-essenciais-para-iniciantes/",
    "https://anfitriaopicarras.com/estrategias-avancadas-para-maximizar-reservas-em-seu-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/aceite-animais-de-estimacao-e-lucre-mais-com-aluguel-por-temporada/",
    "https://anfitriaopicarras.com/como-melhorar-reservas-e-avaliacoes-em-alugueis-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-a-melhor-escolha-para-viagens-confortaveis-e-seguras/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-a-melhor-escolha-para-viagens-em-familia/",
    "https://anfitriaopicarras.com/cachacaria-vo-bertola-o-melhor-da-cachaca-artesanal-e-produtos-coloniais-em-balneario-picarras/",
    "https://anfitriaopicarras.com/como-cuidar-da-limpeza-do-imovel-para-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/o-mercado-de-airbnb-no-brasil-em-2025-perspectivas-e-tendencias/",
    "https://anfitriaopicarras.com/como-investir-em-um-imovel-para-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/onde-investir-em-um-imovel-para-alugar-por-temporada/",
    "https://anfitriaopicarras.com/viajando-com-criancas-por-que-escolher-um-imovel-de-temporada/",
    "https://anfitriaopicarras.com/7-razoes-para-escolher-um-aluguel-de-temporada-para-sua-viagem-para-picarras/",
    "https://anfitriaopicarras.com/onde-investir-em-um-imovel-para-alugar-por-temporada-2/",
    "https://anfitriaopicarras.com/como-decorar-a-cozinha-de-um-imovel-de-temporada/",
    "https://anfitriaopicarras.com/4-motivos-para-comprar-uma-casa-de-ferias/",
    "https://anfitriaopicarras.com/os-7-principais-desafios-legais-ao-alugar-um-imovel-por-temporada/",
    "https://anfitriaopicarras.com/tudo-sobre-a-legislacao-de-locacao-por-temporada-no-brasil/",
    "https://anfitriaopicarras.com/10-dicas-essenciais-para-comprar-uma-casa-de-ferias-fora-do-estado/",
    "https://anfitriaopicarras.com/maximize-seus-lucros-com-a-gestao-de-temporada-em-balneario-picarras/",
    "https://anfitriaopicarras.com/quais-sao-as-principais-atracoes-turisticas-em-balneario-picarras/",
    "https://anfitriaopicarras.com/o-que-fazer-em-balneario-picarras-durante-a-noite/",
    "https://anfitriaopicarras.com/locacao-por-temporada-conheca-seus-direitos-e-evite-problemas-legais/",
    "https://anfitriaopicarras.com/viajando-com-criancas-por-que-escolher-um-imovel-de-temporada-2/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-descubra-as-propriedades-mais-exclusivas-em-balneario-picarras/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-como-maximizar-seus-ganhos-como-proprietario-de-imoveis/",
    "https://anfitriaopicarras.com/checklist-de-preparacao-para-alugar-no-airbnb-tudo-o-que-voce-precisa-saber/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-dicas-para-encontrar-hospedagens-proximas-a-atividades-ao-ar-livre/",
    "https://anfitriaopicarras.com/mantendo-se-disponivel-para-responder-as-mensagens-dos-hospedes/",
    "https://anfitriaopicarras.com/como-alugar-sua-propriedade-no-airbnb-guia-completo/",
    "https://anfitriaopicarras.com/alugue-apenas-quando-quiser-o-imovel-e-seu/",
    "https://anfitriaopicarras.com/dicas-para-viajantes-economize-tempo-e-dinheiro/",
    "https://anfitriaopicarras.com/barco-pirata-picarras/",
    "https://anfitriaopicarras.com/ahoy-marujos-embarquem-em-uma-aventura-inesquecivel-no-passeio-de-barco-pirata-em-picarras/",
    "https://anfitriaopicarras.com/como-ser-um-anfitriao-de-temporada-de-sucesso-em-picarras/",
    "https://anfitriaopicarras.com/como-receber-bem-seus-hospedes-em-alugueis-de-temporada-2/",
    "https://anfitriaopicarras.com/dicas-de-decoracao-para-quartos-pequenos-no-aluguel-de-temporada/",
    "https://anfitriaopicarras.com/aluga-se-um-paraiso-em-picarras/",
    "https://anfitriaopicarras.com/5-dicas-essenciais-para-fotos-de-imoveis-de-temporada/",
    "https://anfitriaopicarras.com/como-receber-bem-seus-hospedes-em-alugueis-de-temporada/",
    "https://anfitriaopicarras.com/como-a-tecnologia-esta-transformando-a-gestao-de-imoveis-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/turismo-de-experiencia-o-que-e-e-qual-a-sua-importancia/",
    "https://anfitriaopicarras.com/atrair-hospedes/",
    "https://anfitriaopicarras.com/melhor-plataforma-aluguel/",
    "https://anfitriaopicarras.com/locacao-por-temporada-entenda-seus-direitos-como-anfitriao-em-picarras/",
    "https://anfitriaopicarras.com/imoveis-temporada-em-balneario-picarras/",
    "https://anfitriaopicarras.com/o-que-levar-na-mala/",
    "https://anfitriaopicarras.com/alugar-no-airbnb-guia-completo/",
    "https://anfitriaopicarras.com/como-se-tornar-um-anfitriao-no-airbnb-requisitos-e-dicas/",
    "https://anfitriaopicarras.com/guia-rapido-preparacao-para-receber-hospedes-no-airbnb/",
    "https://anfitriaopicarras.com/beto-carrero-world/",
    "https://anfitriaopicarras.com/o-que-fazer-em-picarras/",
    "https://anfitriaopicarras.com/anfitriao-de-temporada/",
    "https://anfitriaopicarras.com/praia-de-balneario-picarras/",
    "https://anfitriaopicarras.com/proprietario-aluguel-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/airbnb-o-que-e/",
    "https://anfitriaopicarras.com/como-funciona-o-airbnb/",
    "https://anfitriaopicarras.com/aluguel-de-verao-em-balneario-picarras-no-airbnb/",
    "https://anfitriaopicarras.com/aluguel-de-airbnb-picarras/",
    "https://anfitriaopicarras.com/aluguel-balneario-picarras-no-airbnb/",
    "https://anfitriaopicarras.com/gastronomia-de-picarras/",
    "https://anfitriaopicarras.com/airbnb-picarras/",
    "https://anfitriaopicarras.com/anfitriao-profissional-picarras/",
    "https://anfitriaopicarras.com/airbnb-picarras-2/",
    "https://anfitriaopicarras.com/por-que-escolher-um-airbnb-em-picarras/",
    "https://anfitriaopicarras.com/museu-oceanografico-univali-uma-viagem-ao-fundo-do-mar/",
    "https://anfitriaopicarras.com/as-vantagens-de-se-hospedar-em-uma-casa-com-piscina/",
    "https://anfitriaopicarras.com/aceitar-animais-de-estimacao-pode-aumentar-sua-renda/",
    "https://anfitriaopicarras.com/aluguel-de-temporada-proximo-ao-beto-carrero-world-como-escolher-a-melhor-opcao/",
    "https://anfitriaopicarras.com/5-erros-que-todo-iniciante-no-airbnb-comete-e-como-evitar-se-voce-quer-ser-um-anfitriao-de-temporada-em-picarras/",
    "https://anfitriaopicarras.com/como-se-destacar-como-anfitriao-de-temporada-em-picarras-5-dicas-que-valem-ouro/",
    "https://anfitriaopicarras.com/por-que-ser-anfitriao-de-temporada-em-picarras-pode-mudar-a-sua-vida/",
    "https://anfitriaopicarras.com/desvendando-o-airbnb-dicas-de-um-anfitriao-de-temporada-em-picarras-para-o-sucesso/"
]

blog_dir = r"c:\Users\Osmar Junior\Documents\01 Antigravity\Anfitriao-Picarras\anfitriao-piçarras\src\content\blog"
existing_files = os.listdir(blog_dir)

missing = []
for url in sitemap_urls:
    slug = url.replace("https://anfitriaopicarras.com/", "").strip("/")
    if f"{slug}.md" not in existing_files:
        missing.append(url)

print(f"Encontrados {len(missing)} posts faltando:")
for m in missing:
    print(m)
